name: Build

concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - test-main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          path: "src"

      - name: Set build branch variable
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "branch=builds" >> $GITHUB_OUTPUT
          else
            echo "branch=test-builds" >> $GITHUB_OUTPUT
          fi

      - name: Checkout Build Artifacts Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.vars.outputs.branch }}
          path: "builds"

      - name: Checkout Aliucord
        uses: actions/checkout@v3
        with:
          repository: "Aliucord/Aliucord"
          path: "repo"

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make generateUpdaterJson
          cp **/build/*.zip $GITHUB_WORKSPACE/builds
          cp build/updater.json $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build $GITHUB_SHA" || exit 0
          git push
